import { Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

// const manropeSans = Manrope({
// 	variable: "--font-manrope-sans",
// 	subsets: ["latin"],
// 	preload: true,
// 	weight: ["200", "400", "500", "600", "700", "800"],
// 	display: "swap",
// });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={` antialiased`}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
